on:
  schedule:
    # Se ejecuta a las 3:00 AM de Venezuela (7:00 AM UTC) los domingos (0) y viernes (5)
    - cron: '0 7 * * 0,5'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/products?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
